[package]
name = "graphapp"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui_plot = "0.32.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "3.0"
egui_extras = { version = "0.31.1", features = ["syntect"] }
syntect = "5.0"
boa_engine = "0.20.0"