[package]
name = "graphapp"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = "0.9"
eframe = "0.31.1"
egui_plot = "0.32.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"